### ISSUE TITLE
GitHub documentation: Update nsc-events ReadMe

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/nsc-events-android#124]
As a technical project manager, I will want to ensure that my documentation is thorough, complete, and consistent with other client repositories. Therefore, I will work on the "main" repo for nsc-events.

Relates to: #116

**Comment by taylorpapke** [comment]
@TroyFPV48 I am reassigning you to #135 since it is a user story that was never assigned for Sprint 4 and needs to be completed. Leadership team will complete documentation as we need all of our developers wrapping up the development portion of this project. My apologies for the last minute communication and changes. Thanks for creating the issues and the examples you provided!

**Comment by brandondombrowsky** [comment]
@SeattleColleges/leadership This Issue needs to be reassigned after unassigning myself.

**Comment by taylorpapke** [comment]
@brandondombrowsky, this was a little confusing since it was an issue on nsc-events-android but this is the issue for your PR https://github.com/SeattleColleges/nsc-events/pull/20. Reassigning this to you since I see that you did the work for this.
